docker compose added; datasource and dashboard are provisioned
z-open-data/odp-stack-monitoring pull request #1
Opened 2024-08-07 11:43 UTC by vmichalkevicius-rocket

- docker compose with prometheus and grafana created
- prometheus datasource provisioned on startup
- sample ODP Connect dashboard provisioned on startup

2024-08-21 09:31 UTC, ghannington-Rocket commented on docker-compose.yaml
> +     # port number on the left hand side can be changed to other value if 9090 is beeing in use
Delete "beeing"

2024-08-21 09:31 UTC, ghannington-Rocket commented on docker-compose.yaml
> +     # port number on the left hand side can be changed to other value if 3000 is beeing in use
Delete "beeing"

2024-08-21 09:31 UTC, ghannington-Rocket commented on docker-compose.yaml
> +     # dashboards to privision
Typo: replace "pr**i**vision" with "pr**o**vision"

2024-08-21 09:31 UTC, ghannington-Rocket commented on readme.md
> +- in dedicated docker based environment
Nit: in prose (as opposed to, for example, commands), when referring to the Docker platform, refer to "Docker" with a capital D, not "docker".

2024-08-22 00:56 UTC, davdai01 requested changes

2024-08-22 00:56 UTC, davdai01 commented on readme.md
> +Clone the project repository.
This line should probably be moved to the `## Dedicated Docker setup` section, as this is not needed for `## Existing Prometheus/Grafana setup`

2024-08-22 00:56 UTC, davdai01 commented on config/prometheus/prometheus.yaml
> +    scrape_interval: 5s
This line is probably not needed. `5s` is unnecessary. The default `15s` should be fine.

2024-08-22 08:07 UTC, davdai01 approved these changes

2024-09-04 07:12 UTC, merged